// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOELThHWQR7FrrgMkDmKF8uLBah_J6nlI',
    appId: '1:1011977839941:web:bdf61728216ab8bfa60a2c',
    messagingSenderId: '1011977839941',
    projectId: 'gudang-sppg',
    authDomain: 'gudang-sppg.firebaseapp.com',
    storageBucket: 'gudang-sppg.firebasestorage.app',
    measurementId: 'G-8CXM5MC1RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbe07i0kyvsOd4GKmAbVF3NBwlCjHeU9U',
    appId: '1:1011977839941:android:6b94eb3ecc8de511a60a2c',
    messagingSenderId: '1011977839941',
    projectId: 'gudang-sppg',
    storageBucket: 'gudang-sppg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqIjFCN1tUD7dTDIdb5il7_R8FJOUQ0PA',
    appId: '1:1011977839941:ios:9336b613509a7946a60a2c',
    messagingSenderId: '1011977839941',
    projectId: 'gudang-sppg',
    storageBucket: 'gudang-sppg.firebasestorage.app',
    iosBundleId: 'com.example.gudangApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqIjFCN1tUD7dTDIdb5il7_R8FJOUQ0PA',
    appId: '1:1011977839941:ios:9336b613509a7946a60a2c',
    messagingSenderId: '1011977839941',
    projectId: 'gudang-sppg',
    storageBucket: 'gudang-sppg.firebasestorage.app',
    iosBundleId: 'com.example.gudangApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOELThHWQR7FrrgMkDmKF8uLBah_J6nlI',
    appId: '1:1011977839941:web:44a9cb996798258ca60a2c',
    messagingSenderId: '1011977839941',
    projectId: 'gudang-sppg',
    authDomain: 'gudang-sppg.firebaseapp.com',
    storageBucket: 'gudang-sppg.firebasestorage.app',
    measurementId: 'G-TD1XH0WP2P',
  );
}
