// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApKtWI9QkP1bfeBLP5kgTtEDOg8dfd7xA',
    appId: '1:642699036603:web:941c44dbf016421646269e',
    messagingSenderId: '642699036603',
    projectId: 'gudang-sppg-dev',
    authDomain: 'gudang-sppg-dev.firebaseapp.com',
    storageBucket: 'gudang-sppg-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlVHpunj0U90374uSq1G7UmXokQ1eLaI',
    appId: '1:642699036603:android:44449ced9412afb846269e',
    messagingSenderId: '642699036603',
    projectId: 'gudang-sppg-dev',
    storageBucket: 'gudang-sppg-dev.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApKtWI9QkP1bfeBLP5kgTtEDOg8dfd7xA',
    appId: '1:642699036603:web:f10abd505d464a0446269e',
    messagingSenderId: '642699036603',
    projectId: 'gudang-sppg-dev',
    authDomain: 'gudang-sppg-dev.firebaseapp.com',
    storageBucket: 'gudang-sppg-dev.firebasestorage.app',
  );
}
